/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TodoResponse } from './TodoResponse';
import {
    TodoResponseFromJSON,
    TodoResponseFromJSONTyped,
    TodoResponseToJSON,
} from './TodoResponse';

/**
 * 
 * @export
 * @interface CreateTodoResponse
 */
export interface CreateTodoResponse {
    /**
     * 
     * @type {TodoResponse}
     * @memberof CreateTodoResponse
     */
    createdTodo?: TodoResponse;
}

/**
 * Check if a given object implements the CreateTodoResponse interface.
 */
export function instanceOfCreateTodoResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateTodoResponseFromJSON(json: any): CreateTodoResponse {
    return CreateTodoResponseFromJSONTyped(json, false);
}

export function CreateTodoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTodoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdTodo': !exists(json, 'createdTodo') ? undefined : TodoResponseFromJSON(json['createdTodo']),
    };
}

export function CreateTodoResponseToJSON(value?: CreateTodoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdTodo': TodoResponseToJSON(value.createdTodo),
    };
}

