/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TodoResponse } from './TodoResponse';
import {
    TodoResponseFromJSON,
    TodoResponseFromJSONTyped,
    TodoResponseToJSON,
} from './TodoResponse';

/**
 * 
 * @export
 * @interface GetTodosResponse
 */
export interface GetTodosResponse {
    /**
     * 
     * @type {Array<TodoResponse>}
     * @memberof GetTodosResponse
     */
    todos?: Array<TodoResponse>;
}

/**
 * Check if a given object implements the GetTodosResponse interface.
 */
export function instanceOfGetTodosResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetTodosResponseFromJSON(json: any): GetTodosResponse {
    return GetTodosResponseFromJSONTyped(json, false);
}

export function GetTodosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTodosResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'todos': !exists(json, 'todos') ? undefined : ((json['todos'] as Array<any>).map(TodoResponseFromJSON)),
    };
}

export function GetTodosResponseToJSON(value?: GetTodosResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'todos': value.todos === undefined ? undefined : ((value.todos as Array<any>).map(TodoResponseToJSON)),
    };
}

