/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoResponse
 */
export interface TodoResponse {
    /**
     * 
     * @type {string}
     * @memberof TodoResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TodoResponse
     */
    text?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoResponse
     */
    checked?: boolean;
}

/**
 * Check if a given object implements the TodoResponse interface.
 */
export function instanceOfTodoResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TodoResponseFromJSON(json: any): TodoResponse {
    return TodoResponseFromJSONTyped(json, false);
}

export function TodoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'checked': !exists(json, 'checked') ? undefined : json['checked'],
    };
}

export function TodoResponseToJSON(value?: TodoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'text': value.text,
        'checked': value.checked,
    };
}

